[project]
name = "bimba-go-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "protobuf>=6.31.0",
    "pydantic>=2.11.4",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
