services:
  - type: web
    name: bimba-go-backend
    runtime: python
    buildCommand: uv pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars: 
      - key: PORT
        value: 8000
    # Dodaj zmienne środowiskowe, jeśli będą potrzebne (np. API_KEY)
    # envVars:
    #   - key: MY_API_KEY
    #     value: your_secret_key
